# Generated by Django 4.2.1 on 2023-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_options_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
